jobs:
    main:
        requires: [~commit, ~pr, ~sd@113:main]
        image: node:8
        steps:
            - install-dependencies: npm install
            - test: npm test
    deploy:
        requires: [main]
        image: node:8
        steps:
            - install-dependencies: . ./bin/install.sh
            - test: npm test
            - heroku-deploy: . ./bin/heroku_deploy.sh
        secrets:
            - HEROKU_API_KEY
            - HEROKU_APP
